### ISSUE TITLE
Is Plugin Still Active/Working?

### ISSUE THREAD

**Issue by mcanady** [cabrerahector/wordpress-popular-posts-feed#1]
Hi, is this plugin still working with current wordpress/wordpress popular posts?

1. Posts in different categories in the feed
2. One random URL showing up as a syndicated attribution at the end of each item in the feed. I don't know if it comes from the wpp or the wpp feed plugin..

Examples below, wordpress 5.8, wpp 1.41

https://sdbn.org/category/san-diego-biotech-news/feed/popular-posts
https://labn.org/category/los-angeles-biotech-news/feed/popular-posts

**Comment by cabrerahector** [comment]
Hi @mcanady,

> is this plugin still working with current wordpress/wordpress popular posts?

Yep, just tried it on my test site with the latest version of the WPP plugin and it seems to be working fine.

> Posts in different categories in the feed

This plugin does allow you to filter your feed by post category if that's what you're asking. Check the [Customization](https://github.com/cabrerahector/wordpress-popular-posts-feed/tree/1.0.1#customization) section for more details and if you have any questions don't hesitate to ask.

> One random URL showing up as a syndicated attribution at the end of each item in the feed. I don't know if it comes from the wpp or the wpp feed plugin

Can't find that "syndicated attribution" text on my feed so my guess is that this is coming from another plugin, from your theme, or it's something you/your editor inserted into your posts content manually.

![wpp-feed-screenshot](https://user-images.githubusercontent.com/3186556/131256667-7a0de4f9-48ac-488d-8372-ab6f6f1b5884.png)

**Comment by mcanady** [comment]
Thanks Hector, I'll keep digging. I did think though that the URL below would return a feed of posts just from this category in the URL, is that incorrect?

https://labn.org/category/los-angeles-biotech-news/feed/popular-posts

**Comment by cabrerahector** [comment]
Yep, that's not really how this plugin works :P Although it might be a good idea to have it automatically filter posts by the current category, I'll have a look into it. On a second thought, it might not be necessary to change the plugin to achieve this. I think I have an idea.

**Comment by cabrerahector** [comment]
Alright, please add this code snippet to your theme's functions.php file to have the feed automatically filter posts by category when viewing a category archive feed:

```php
/**
 * Have the WPP feed automatically filter posts by category
 * when viewing a category archive feed.
 */
function wp3951_my_popular_feed_options( $args ) {
    if ( is_category() ) {
        $category = get_queried_object();
        $args['taxonomy'] = 'category';
        $args['term_id'] = $category->term_id;
    }

    return $args;
}
add_filter('popular_posts_feed_args', 'wp3951_my_popular_feed_options', 10);
```

**Comment by mcanady** [comment]
Thanks so much @cabrerahector, it worked! It took awhile for me to test on wordpress and wordpress mu, it seems to work on both. Do you have a place I can make a donation for your work?

**Comment by cabrerahector** [comment]
Glad to know that so thanks for reporting back! This will surely help future users as well :)

> Do you have a place I can make a donation for your work?

That's very generous of you so many thanks in advance :)

[Buy me a coffee](https://www.buymeacoffee.com/cabrerahector) | [PayPal Me](https://paypal.me/cabrerahector) | [Ko-fi](https://ko-fi.com/cabrerahector)

**Comment by mcanady** [comment]
Hi Hector--This plugin stopped working a few weeks ago. Not sure if it coincided with my wordpress update to 6.0.1, it doesn't seem to coincide but I'm not sure.

Here is an example of the feed. It throws a 404 error when viewed in browser, but with the "super RSS reader" wordpress plugin, all of the popular posts are returned, not just in 1 category:
https://sfbn.org/category/san-francisco-biotech-news/feed/popular-posts

Wordpress 6.0.1
Wordpress popular posts 6.0.3 (I don't remember updating it?)
Popular posts feed 1.0

Thanks! Will happily make another donation regardless of the outcome ;)

Mary

**Comment by cabrerahector** [comment]
Hi @mcanady!

Yeah, someone else reached out to me via email a couple of days ago to report something similar.

Please grab the [latest version of the plugin](https://github.com/cabrerahector/wordpress-popular-posts-feed/releases/latest) and install it on your site. That should hopefully fix the problem :)

P.S.: Donation is not really required, it's my fault to begin with for not keeping this plugin up to date :P I sincerely appreciate the gesture though so thanks for your kindness.

**Comment by mcanady** [comment]
Hi--Thanks so much, I just installed the Popular Posts 1.0.2 and it seems to be working! Don't feel guilty about not providing frequent updates on a free plugin!

Mary
